### ISSUE TITLE
[BUG] Maximum execution time exceeded

### ISSUE THREAD

**Issue by RickvanB** [AnimalDesign/bolt-translate#97] opened 2017-01-17 18:49 UTC
Hello,

I installed the plugin on my shared hosting, because openssl doens't work locally. The homepage works fine, but whenever I'm trying to visit another page on my website. It get's in an endless loop and after that I get the message from Bolt that my maximum execution time is exceeded.

Details:
- Latest version of Translate
- Installed via Bolt CMS
- Bolt version 3.2.3
- PHP version 5.6
- Webserver: Apache

Translate config:
```
# The locales the site should be available in
locales:
    nl_NL:
        label: Nederlands
        slug: nl
    en_GB:
        label: Engels
        slug: en

routing_override: true
menu_override: true
url_generator_override: true
translate_slugs: true
use_accept_language_header: true
```
I think it has something todo with the routing, but I'm not an expert in Bolt..
Anybody had this problem before and can help me?

Thanks in advance.

**Comment by SahAssar** [comment] 2017-01-20 19:09
Hmm, I've never seen it go looping off like that, Could you perhaps check the debug profiler so see if that gives us any more info?

**Comment by RickvanB** [comment] 2017-01-22 14:30
Hi, thanks for answering! Where can I find that.
This is the url: https://test.inchplastics.nl/nl/pagina/over-ons. So you can check by yourself if necessary.

**Comment by SahAssar** [comment] 2017-01-22 20:04
Hmm, it looks like it's hitting that execution time in monolog, but the only place we use the logger is in the menu, here: https://github.com/AnimalDesign/bolt-translate/search?utf8=%E2%9C%93&q=logger, so I'm guessing it's something to do with the menu. Could you post your menu.yml? Also, the debugger can be turned on and off in the main config.yml and is then shown on the bottom of every page.

**Comment by RickvanB** [comment] 2017-01-22 21:04
Debug is turned on in the main config.yml, but for some reason it doens't show up when the error is thrown.

My menu.twig (the most important, the rest is just html):
          ```
<nav id="site-navigation" class="clearfix" role="navigation">
            {% setcontent pages = 'pages/latest/6' orderby 'id'  %}
            <div class="menu-container">
              {% for page in pages %}
                {% if loop.first %}<ul id="menu-main-menu" class="menu">{% endif %}
                <li class="menu-item {% if page|current %}current-menu-item{% endif %}"><a href="{{ page.link }}">{{ page.title|trimtext(12) }}</a></li>
                {% if loop.last %}</ul>{% endif %}
              {% endfor %}
            </div>
          </nav>
```

As I see now, my menu.yml is never changed (just default stuff), maybe that's the problem?
```
main:
    - label: Home
      title: This is the first menu item.
      path: homepage
      class: first
    - label: Second item
      path: entry/1
      submenu:
          - label: Sub 1
            path: entry/2
          - label: Sub 2
            class: menu-item-class
            path: entry/3
          - label: Sub 3
            path: entry/4
          - label: Sub 4
            class: sub-class
            path: page/3
    - label: All pages
      path: pages/
    - label: The Bolt site
      link: http://bolt.cm
      class: last
```

**Comment by RickvanB** [comment] 2017-01-25 17:40
Is it possible to temporarily disable the logger?

**Comment by RickvanB** [comment] 2017-02-03 18:22
Any solution? If you want, I can make a repo from my current site, if that helps.

**Comment by SahAssar** [comment] 2017-02-03 23:15
@RickvanB Sorry, I haven't had the time to look deeper at this :(

I haven't been able to reproduce it in a fresh install, but I'll check it out more in the coming days. Sorry for the delay!

**Comment by RickvanB** [comment] 2017-02-08 15:57
@SahAssar Thanks for you answer and for looking into it deeper! Is it a possibility to temporarily disable the logger? So that I can move on with the website.

**Comment by SahAssar** [comment] 2017-02-16 17:18
@RickvanB We've been having one of those nightmare projects at work, so still no luck on this. Could you perhaps try the latest dev-master of translate? A bunch of small issues have been fixed in that, and this might have been effected.

**Comment by RickvanB** [comment] 2017-02-16 18:38
@SahAssar I've updated Translate to 4.0.2, but still the same problem. When I set debug to true I get an empty response from Chrome. If debug is false I get only an error page, which is probably the error in my first post.

**Comment by SahAssar** [comment] 2017-02-16 19:33
@RickvanB Yeah, sorry, I botched that release... :/ I tagged 4.0.3 which should fix that WSOD problem, could you try that?

**Comment by RickvanB** [comment] 2017-02-17 10:38
@SahAssar I installed 4.0.4 yesterday and it seems like it's working again! 👍 . Only thing that I need to find out now what my slug for english pages is. Anyway, many thanks for your help!

**Comment by SahAssar** [comment] 2017-02-18 10:21
Great, closing this then! :)

**Closed by SahAssar** 2017-02-18 10:21 UTC
