### ISSUE TITLE
[BUG] Doesn't save data on repeater fields

### ISSUE THREAD

**Issue by zomars** [AnimalDesign/bolt-translate#31] opened 2016-07-14 22:10 UTC
I got a website that use repeater fields a lot. I tried to configure my `contenttypes.yml` like this:

```yaml
repeater:
	type: repeater
	is_translateable: true
	fields:
		repeattitle:
			type: text
			is_translateable: true
```

Maybe I'ts not supported but I couldn't find anything in the docs.

Thanks for keeping this plugin so great, cheer mate!

**Comment by madc** [comment] 2016-07-14 22:23
I think, that repeaters are not yet implemented, see [#24](https://github.com/AnimalDesign/bolt-translate/issues/24#issuecomment-232145559)

**Comment by zomars** [comment] 2016-07-14 22:25
I see, still this counts as a bug right? I wasn't aware it was mentioned there.

**Comment by SahAssar** [comment] 2016-07-15 08:37
@zomars They should be implemented on the backend, but not on the frontend due to bolt/bolt/issues/5533. Do they not work on the backend for you?

**Comment by zomars** [comment] 2016-07-15 16:29
I think the reason it wasn't working in the backend was because of #32. I'll update and test it again.

**Comment by SahAssar** [comment] 2016-07-18 09:08
As of bdac3fa repeaters should work both in front and back end, @zomars could you check if the issue is solved for you? Perhaps I can then tag a release of the ext :)

**Comment by zomars** [comment] 2016-07-18 17:03
Backend is working fine, but somehow translated repeaters are not rendering at all in the front, only the default locale.

**Comment by zomars** [comment] 2016-07-18 17:08
Some additional info:
```yaml
repeater:
    type: repeater
    group: repeater
    is_translateable: true
    fields:
        repeattitle:
            type: text
        repeatcontent:
            type: html
        repeatimage:
            type: image
            extensions: [ gif, jpg, png ]
        repeatlink:
            type: text
        repeatbgcolor:
            type: select
            values: [ "white", "light-gray" ]
```
Also my current theme is css only modified version of the current `base-2016` theme

**Comment by SahAssar** [comment] 2016-07-18 18:40
@zomars Just to make debugging easier/more precise could I get your bolt version (and latest commit if using dev-master or release/3.0), database type and php version? Also, does other content in that contenttype (non-repeaters) translate correctly? 

Also it seems like 5542 has not been "up-merged" into master (as of the time of writing) so if you are using bolt/master could you check if switching to latest release/3.0 fixes the issue?

Sorry if this is a lot to ask of you!

**Comment by zomars** [comment] 2016-07-18 18:48
Sure! I'm using Bolt (dev-release/3.0 2193fa7), MySQL and PHP 5.5.34. The other content is translating just fine, no problems with routing, labels and forms.

**Comment by SahAssar** [comment] 2016-07-18 18:53
Hmm, before I setup a php 5.5 and MySQL server, could you try to turn on/show all php errors/warnings (if not on already) and see if it gives you anything and also check in the DB if the "$locale_data" column shows the repeaters in the json data for that locale?

Thank you so much for your bughunting :)

**Comment by SahAssar** [comment] 2016-07-18 19:05
Also, (forgot about this) if possible please post which commit of translate you are on!

**Comment by zomars** [comment] 2016-07-18 19:08
Yes, the json data is appearing in the en_locale column (in this case), and php is not showing any errors.
![captura de pantalla 2016-07-18 a las 1 04 46 p m](https://cloud.githubusercontent.com/assets/3504472/16926961/6084033c-4ce8-11e6-8804-4b5f8d28dc9c.png)
![captura de pantalla 2016-07-18 a las 1 04 59 p m](https://cloud.githubusercontent.com/assets/3504472/16926963/64afbfd2-4ce8-11e6-9a47-3aa9a2cff84a.png)

Also, I'm using the translate (dev-master 24fe997).

**Comment by SahAssar** [comment] 2016-07-18 19:15
zomars: Just to be sure about one detail... You are getting untranslated/original repeaters, not empty ones when going to non-default locales, right?

**Comment by zomars** [comment] 2016-07-18 19:17
I'm getting nothing at all on non-default locale repeaters.

**Comment by zomars** [comment] 2016-07-18 19:17
Back-end is fine tho.

**Comment by SahAssar** [comment] 2016-07-18 20:39
Turned out to be an outdated file, so resolved via slack :) please let me know if you have any other issues with the extension @zomars!

**Closed by SahAssar** 2016-07-18 20:39 UTC

**Comment by zomars** [comment] 2016-07-18 20:42
Will do! Thanks for your help!
