### ISSUE TITLE
Can't edit English content

### ISSUE THREAD

**Issue by fojtcz** [AnimalDesign/bolt-translate#28] opened 2016-07-13 15:20 UTC
Hi,

my default language in Bolt is Czech, I can create new entries with no problem. Everything is saved in database. But if I go to list of entries and try to open my English entry. I see only Czech texts.

Sorry for my English,
Martin

**Comment by SahAssar** [comment] 2016-07-13 15:51
Hey @fojtcz,

So, both the default language (first in locales) and your bolt backend language is Czech, right? Is this on bolt 2.2 or 3.0?  Also, can you check in your browsers dev tools if you have any errors there?

**Comment by fojtcz** [comment] 2016-07-13 17:06
Hi @SahAssar,

yeah, i set my default language to Czech. I am using latest Bolt 3.0. I don't see any errors in dev tools.

**Comment by SahAssar** [comment] 2016-07-13 17:37
@fojtcz could you post your contenttypes.yml, your extension config (translate.animal.yml) and your config.yml so that I can reproduce the issue?

Thanks!

**Comment by SahAssar** [comment] 2016-07-13 17:40
@fojtcz Oh, wait, you're using the latest stable 3.0? Cause this will only work in the dev version of bolt 3.0 until 3.0.10 is released...

**Comment by fojtcz** [comment] 2016-07-14 05:03
@SahAssar yes, i am using stable version of Bolt 3.0.9.

my `translate.animal.yml`

```
locales:
    cs_CZ:
        label: Čeština
        slug: cs
    en_GB:
        label: English
        slug: en

routing_override: false
menu_override: false
translate_slugs: false
```

**Comment by SahAssar** [comment] 2016-07-14 05:51
@fojtcz Well, then that's the issue... This extension will not work with 3.0.9 or earlier versions. It will only work with stable when the next bolt version is released. Please see #24.

If your interested in why, it's because there was a small bug in PRE_HYDRATE, so [this](https://github.com/AnimalDesign/bolt-translate/blob/master/src/TranslateExtension.php#L110-L131) callback basically does nothing in 3.0.9.

I'm closing this, please feel free open a new issue if you run into the same issue on a compatible bolt version! :)

**Closed by SahAssar** 2016-07-14 05:51 UTC
