### ISSUE TITLE
[BUG?] Extension doesn't keep default locale

### ISSUE THREAD

**Issue by peterboorsma** [AnimalDesign/bolt-translate#101] opened 2017-02-06 08:47 UTC
The docs say that the first locale added to the translate.animal.yml is used as the default locale.
In my case, frontend and backend both keep using EN as the default.
nl_NL is the locale set in config.yml and the first in translate.animal.yml.

Am I the only one experiencing this? 

```
locales:
    nl_NL:
        label: Nederlands
        slug: nl
    en_GB:
        label: English
        slug: en

```

-------
 - Translate Version: dev-master
 - Bolt Version: 3.2.6

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

 1. **Bug summary**: Write a short summary of the bug. Try to pinpoint it as
    much a possible. Try to state the _actual problem_, and not just what you
    _think_ the solution might be.
 2. **Specifics**: Mention the URL where this bug occurs, if applicable. What
    version of Bolt are you using (down to the very last digit!), and what
    method did you use to install it? What browser and version are you using?
    Please mention if you've checked it in other browsers as well. Please
    include *full error messages* and *screenshots* if possible.
 3. **Steps to reproduce**: Clearly mention the steps to reproduce the bug.
 4. **Expected result**: What did you _expect_ that would happen on your Bolt
    site? Describe the intended outcome after you did the steps mentioned
    before.
 5. **Actual result**: What is the actual result of the above steps? So,
    describe the behaviour of the bug. Please, please include **Error messages**
    and screenshots. They might mean nothing to you, but they are _very_ helpful
    to us.

**Comment by SahAssar** [comment] 2017-02-15 18:49
@peterboorsma Sorry for the late reply... Could you perhaps try turning off the automatic language detection in the config? It might be what's causing this for you.

**Comment by SahAssar** [comment] 2017-02-18 10:34
We has a similar issue on IRC a little while ago and the issue was the automatic language detection. Basically it tries to direct you to the preferred language set in the browser, after a locale has been detected it is made "sticky" though, and will not direct you back. It can be turned off in the config though.

Closing for now as "it's not a bug, it's a feature" (Always wanted to say that in an issue tracker 😆  ).

**Closed by SahAssar** 2017-02-18 10:34 UTC
